export const screenNames = {
  login: 'login',
  signup: 'signup',
  home: 'home',
  room: 'room',
  profile: 'profile',
  create_new_room: 'Create New Room',
  room_info: 'Room Information',
  room_expense_form: 'Expense Form',
  add_room_category: 'Categories',
  members: 'Room Members',
  add_new_member: 'Add New Member',
  month: 'Financial Months',
  expense_list: 'Expense List',
};
